# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alifeui.ui'
#
# Created: Thu Aug 12 15:56:55 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ALife(object):
    def setupUi(self, ALife):
        ALife.setObjectName("ALife")
        ALife.resize(830, 803)
        self.centralwidget = QtGui.QWidget(ALife)
        self.centralwidget.setObjectName("centralwidget")
        self.main_view = QtGui.QWidget(self.centralwidget)
        self.main_view.setGeometry(QtCore.QRect(20, 10, 791, 311))
        self.main_view.setObjectName("main_view")
        self.reset = QtGui.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(440, 320, 165, 32))
        self.reset.setObjectName("reset")
        self.start_stop = QtGui.QPushButton(self.centralwidget)
        self.start_stop.setGeometry(QtCore.QRect(210, 320, 165, 32))
        self.start_stop.setDefault(False)
        self.start_stop.setObjectName("start_stop")
        self.robot_params_label = QtGui.QLabel(self.centralwidget)
        self.robot_params_label.setGeometry(QtCore.QRect(191, 471, 39, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.robot_params_label.setFont(font)
        self.robot_params_label.setObjectName("robot_params_label")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(21, 405, 161, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(590, 471, 63, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(179, 405, 371, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(667, 402, 72, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(741, 402, 70, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(400, 470, 20, 281))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(552, 402, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 510, 371, 231))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.widget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_2.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.widget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_2.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(430, 510, 381, 231))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtGui.QLabel(self.widget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.widget1)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_3.addWidget(self.comboBox_5, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.widget1)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_3.addWidget(self.comboBox_6, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.comboBox_7 = QtGui.QComboBox(self.widget1)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_3.addWidget(self.comboBox_7, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget1)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.comboBox_8 = QtGui.QComboBox(self.widget1)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_3.addWidget(self.comboBox_8, 3, 1, 1, 1)
        ALife.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ALife)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 22))
        self.menubar.setObjectName("menubar")
        ALife.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ALife)
        self.statusbar.setObjectName("statusbar")
        ALife.setStatusBar(self.statusbar)

        self.retranslateUi(ALife)
        QtCore.QMetaObject.connectSlotsByName(ALife)

    def retranslateUi(self, ALife):
        ALife.setWindowTitle(QtGui.QApplication.translate("ALife", "ALife On An Asteroid", None, QtGui.QApplication.UnicodeUTF8))
        self.reset.setText(QtGui.QApplication.translate("ALife", "Restart Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.start_stop.setText(QtGui.QApplication.translate("ALife", "Start Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.robot_params_label.setText(QtGui.QApplication.translate("ALife", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ALife", "Robot Control Weights:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ALife", "Evolution", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("ALife", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("ALife", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("ALife", "Evolve New", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ALife", "No. Body Sections:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ALife", "No. Legs Per Body Section:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ALife", "Body Density:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ALife", "Leg Density:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ALife", "Algorithm:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ALife", "No. Generations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ALife", "No. Islands:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ALife", "No. Individuals Per Island:", None, QtGui.QApplication.UnicodeUTF8))

